### ISSUE TITLE
Table CSS

### ISSUE THREAD

**Issue by mrozilla** [react-native-community/rn-diff-purge#10]
Hello, cheers for a wonderful package!

I'd be happy to make some CSS-fu updates to the `/docs/index.html` file, wanted to check whether it's still available and whether there's anything specific to know before starting :)

**Comment by pvinis** [comment]
Yep, feel free to do that! What do you have in mind?

**Comment by mrozilla** [comment]
Nothing crazy, just a making it readable :) Is there any build tooling in place or do we just chuck a `<style>` tag into the file directly?

**Comment by pvinis** [comment]
I create the file in the generate-table js script, so I would say we just put things in a <style> and then concat them together or something like that. it doesn't need to be too smart, just to work. now it works but is ugly and hard to navigate 😛. I think I had some ideas on the readme about what to do, but yea, go wild and make it as you think 👍.

**Comment by mrozilla** [comment]
A quick update, I'm still on this, just been busy lately :)

**Comment by ajulien42** [comment]
Hey I made some, it's just css, colors are not great, feel free to modify it.
body {
  margin: 0;
}
table {
  border-collapse: collapse;
}
td,th {
  min-width: 9rem;
  height: 3rem;
  text-align: center;
  background-color: #fff;
}
tr th:nth-child(odd) {
  background-color: #eef3f5;
}
tr:nth-child(even) td:nth-child(odd), 
tr:nth-child(odd) td:nth-child(even)
{
    background-color: #eef3f5;
}

tr:nth-child(even) td:first-child,th:first-child {
  background-color: #eef3f5;
  position: sticky;
  left: 0;
}

tr:nth-child(odd) td:first-child,th:first-child {
  background-color: #cedde2;
  position: sticky;
  left: 0;
}

tr:hover td{
  background-color: #deebe2!important;
  /* #deebe2 */
}
tr:nth-child(odd):hover  td:first-child{
  background-color: #bed9c5!important;
}
td:hover {
  outline: 3px dashed #9ec6aa;
  outline-offset: -3px;
}

**Comment by ajulien42** [comment]
@pvinis Hey so I thinks this issue is kinda dead, so I made some css I minified it, I kinda copied the github style, and it does everything you ask for. I haven't read all your script in details, but if I just put a <style> in index.html, it's not gonna be overwritten by your generate-table.js ?
Anyway here the css minified: 
`<style>body{margin:0;color:#24292e;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Open Sans","Helvetica Neue",sans-serif}a{color:#0366d6;text-decoration:none}a:hover{text-decoration:underline}table{border-collapse:collapse;border-spacing:0}td,th{border:1px solid #dfe2e5;font-size:14px!important;min-width:9rem;height:3rem;text-align:center;background-color:#fff}tr th:nth-child(odd){background-color:#f6f8fa}tr:nth-child(even) td:nth-child(odd),tr:nth-child(odd) td:nth-child(even){background-color:#f6f8fa}th:first-child,tr:nth-child(even) td:first-child{background-color:#f6f8fa;position:sticky;left:0}th:first-child,tr:nth-child(odd) td:first-child{background-color:#e6ebf1;position:sticky;left:0}tr:hover td{background-color:#f1f8ff!important}tr:nth-child(odd):hover td:first-child{background-color:#d8ebff!important}td:hover{outline:2px solid #c8e1ff;outline-offset:-2px}</style>`

**Comment by pvinis** [comment]
I tried to paste it, and my browser kept freaking out. I'll try again.

**Comment by pvinis** [comment]
quick and dirty solution added in https://github.com/react-native-community/rn-diff-purge/commit/e2c3e8ae99726dc748570bf786799ab4b7ae97a4

**Comment by pvinis** [comment]
I will leave this open for now, to see if @mrozilla has an idea about how to improve this even more, or we close it later.

**Comment by mrozilla** [comment]
I'm back! 🎉

Lovely to see the work happening here already! I've taken the already solid solution (lovely colour palette btw) and merged it with my approach (denser data and improved readability) in #19 

Let me know what you think in the PR!
