### ISSUE TITLE
How do PBXBuildFile ref's (referenc, isa, fileRef) work

### ISSUE THREAD

**Issue by pcooney10** [react-native-community/rn-diff-purge#3]
Hey, great project @pvinis, @ncuillery, and @react-native-community !

I have two (potentially related) questions that I'm hoping folks may have some insight on.

### 1. Is there any meaning behind the PBXBuildFile file references? Does changing/not changing them have any meaningful effect during an upgrade?

There is an example in the [`0.56.0...0.57.0`](https://github.com/react-native-community/rn-diff-purge/compare/version%2F0.56.0...version%2F0.57.0?diff=split#diff-47688e69ba4c83d925cb62d0b3fb3528R16) diff that makes some changes around the `libRCTAnimation.a` library:

<img width="1338" alt="Screen Shot 2019-03-12 at 8 19 44 PM" src="https://user-images.githubusercontent.com/11021913/54244734-4e753280-4504-11e9-95c2-7590dfc009e6.png">

Here, some file references are changed, namely the `PBXBuildFile` `reference` and `fileRef`, but I am curious if these changes have any meaningful impact. I did some googling, and wasn't able to come up with too much, but this article seemed to be somewhat helpful: http://www.monobjc.net/xcode-project-file-format.html

In the document, the author(s) state:
> The algorithm used by Xcode to generate the unique identifier [96 bit, represented using a 24 hexadecimal value] seems to be based both on date, sequence and pre-defined values, **but as there is no evidence that these identifiers must follow a generation convention, one can think that arbitrary identifier can be used, as long as they are unique across the document**.

### 2. How are manually linked modules affected when their versions in `package.json` / `node_modules` are updated?
_As a preface, this question is potentially an entirely separate discussion, or should belong on a separate forum (SO), but I think it may related as React Native seems to have a mix of manual linked & CocoaPods based dependencies._

This question is more so geared towards updating third-party libraries that only supporting linking (no CocoaPods option). One such example is [`react-native-community/react-native-image-picker`](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md). It would seem that updating the npm dependency alone will work, as the linked library references an `.xcodeproj` file in the project's `node_modules` folder, but I am not entirely certain. I guess would've expected to see some PBXBuildFile ref's to change in the diff, but I guess this would only happen if the library author generated a completely new `.xcodeproj` between updates.

**Comment by pvinis** [comment]
Glad to hear that you think that, and thanks for using it!

About your first question: the links you have are good resources. A diff like the one in the picture can mean anything of the following
- Xcode just updated and restructured the file, and just generated a new I'd or moved lines around.
- The file was removed and added again to the Xcode project.
- Any other random thing related to Xcode and its file structure.
The important thing in diffs like that one is to make see the change in numbers.

If something is deleted once and added once a few lines below or above, it could be safe to just not do anything.

If there is something added more times than deleted or the other way, then it's best to add that file or remove it. Most times it's a linked framework.

Make sure to add or remove frameworks like that to all your Xcode targets. In the diff it could be added once since it's only one iOS target or maybe twice, one for iOS and one for tvOS, but if you have say three targets, then your diff would be the diff you see times three. Three times added instead of once.

Xcode diffs are always a bit weird but it gets easier the more you do it. You can always try moving things around and seeing the diff on your local git, to get a feel of how it works. It makes sense after a while, but it is still complicated and it could be simpler.

I hope soon we can move to using xcodegen or something similar, so the Xcode project can be declared and generated, without caring about the actual xcodeproj

**Comment by vikrantnegi** [comment]
What I do is that I don't do anything to these lines I just add the new lines that newer react native version shows.

Seems to be working fine for me.

**Comment by pcooney10** [comment]
@pvinis awesome, thanks for the quick & detailed response 😄

So for number **2.** - sans projects that have CocoaPods / podspecs - updating the npm dependency will _not_  update the (manually) linked library?

Building off of our `react-native-image-picker` example, I did a test to see what happens when upgrading a dependency that has changes to a native file( `ImagePickerManager.m` in [v0.26.10...v.0.28.0](https://github.com/react-native-community/react-native-image-picker/compare/v0.26.10...v0.28.0#diff-d8a8dfce7b30e35397fe68d17667d8c5L16)). It seems to have updated `RNImagePicker.xcodeproj` & `ImagePickerManager.m` correctly, without only a `yarn install` install my end.

This makes sense, given that the files are linked directly from `node_modules`. However, when I tried to do the reverse - and revert back to v0.26.10 - I didn't have the same luck 🤷‍♂️. It seems that doing `rm -rf node_modules && yarn install` does the trick, so maybe this could be sufficient for updated non-podspec'ed libraries? This method could also be considered the same as what you're saying about "re-linking", since there's no guarantee Xcode will update the referenced files, but I try to avoid `react-native link` as much as I can since it can be a bit wonky !

For reference, here's a video of me updating `react-native-image-picker` with the experience described above:
[![video illustration](https://i.imgur.com/hE51elm.png)](https://imgur.com/a/Ka1P4yZ)

**Comment by pvinis** [comment]
The files not being updated when you install sounds like a yarn bug. Things in node_modules should be what you yarn install.

In your case it worked, which is great. It might or it might not work if you had added new native files. This I would have to try to see the behavior. But it's kinda what I said before basically. Check the changelog, and see your diff, check what Xcode thinks (red files etc), and always test your app after dep updating.

Good investigation. We want to make things better on the upgrade front, so knowing the problems helps to figure out the best solutions!
